export default {
  SET_FAVOURITE: 'SET_FAVOURITE',
  REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  GET_VIDEO_SOURCE: 'GET_VIDEO_SOURCE',
  SEARCH_VIDEO: 'SEARCH_VIDEO',
};