/**
 * @concept TIMES AS CONSTANTS
*/

const FIVE_MINUTES_IN_SECONDS = 300000;
const SIXTY__MINUTES_IN_SECONDS = 3600000;
const TWO_HOURS_IN_SEC = 7200000;
const THIRTY_DAYS_IN_SEC = 2592000000;

module.exports = {
  FIVE_MINUTES_IN_SECONDS,
  SIXTY__MINUTES_IN_SECONDS,
  THIRTY_DAYS_IN_SEC,
  TWO_HOURS_IN_SEC,
};
